services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # tool: installer
    CORS\Pimcore\WorkflowGUI\Installer\WorkflowGUIInstaller:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('WorkflowGUIBundle')"

