services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # tool: installer
    CORS\Bundle\WorkflowGUIBundle\Installer\WorkflowGuiInstaller:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('WorkflowGuiBundle')"

