imports:
    - { resource: 'services/installer.yml' }

services:
    CORS\Pimcore\WorkflowGui\Resolver\ConfigFileResolver:
        arguments:
            - '%workflow_gui.config%'

    CORS\Pimcore\WorkflowGui\Repository\WorkflowRepository:
        arguments:
            - '@CORS\Pimcore\WorkflowGui\Resolver\ConfigFileResolver'

    CORS\Pimcore\WorkflowGui\Controller\WorkflowController:
        arguments:
            - '@CORS\Pimcore\WorkflowGui\Repository\WorkflowRepository'
            - '@CORS\Pimcore\WorkflowGui\Resolver\ConfigFileResolver'
            - '@kernel'
            - '@Pimcore\Cache\Symfony\CacheClearer'
        tags:
            - { name: controller.service_arguments }
        calls:
            - { method: setContainer, arguments: [ '@service_container' ] }
            - { method: setTokenResolver, arguments: [ '@Pimcore\Security\User\TokenStorageUserResolver' ] }
            - { method: setPimcoreSerializer, arguments: [ '@pimcore.serializer' ] }
