imports:
    - { resource: 'services/installer.yml' }

services:
    CORS\Bundle\WorkflowGUIBundle\Resolver\ConfigFileResolver:
        arguments:
            - '%workflow_gui.config%'

    CORS\Bundle\WorkflowGUIBundle\Repository\WorkflowRepository:
        arguments:
            - '@CORS\Bundle\WorkflowGUIBundle\Resolver\ConfigFileResolver'

    CORS\Bundle\WorkflowGUIBundle\Controller\WorkflowController:
        arguments:
            - '@CORS\Bundle\WorkflowGUIBundle\Repository\WorkflowRepository'
            - '@CORS\Bundle\WorkflowGUIBundle\Resolver\ConfigFileResolver'
            - '@kernel'
            - '@Pimcore\Cache\Symfony\CacheClearer'
        tags:
            - { name: controller.service_arguments }
        calls:
            - { method: setContainer, arguments: [ '@service_container' ] }
